name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  RESOURCE_GROUP: todo-app-rg
  AZURE_CONTAINER_REGISTRY: springtodoapp
  IMAGE_NAME: todo-app

jobs:
#  unit-tests:
#    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
#    runs-on: ubuntu-24.04-arm
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#      - name: Set up JDK 25
#        uses: actions/setup-java@v5
#        with:
#          distribution: 'temurin'
#          java-version: '25'
#          cache: 'maven'
#      - name: Run Unit Tests
#        run: mvn test
#
#  integration-tests:
#    runs-on: ubuntu-24.04-arm
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#      - name: Set up JDK 25
#        uses: actions/setup-java@v5
#        with:
#          distribution: 'temurin'
#          java-version: '25'
#          cache: 'maven'
#      - name: Run Integration Tests
#        run: mvn verify -DskipUTs=true
#
#  build:
#    needs: [ unit-tests, integration-tests ]
#    runs-on: ubuntu-24.04-arm
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#      - name: Set up JDK 25
#        uses: actions/setup-java@v5
#        with:
#          distribution: 'temurin'
#          java-version: '25'
#          cache: 'maven'
#      - name: Build native image
#        run: mvn -Pnative,aot-helper spring-boot:build-image -DskipUTs

  acr :
    runs-on: ubuntu-24.04
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
