name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  RESOURCE_GROUP: todo-app-rg
  AZURE_CONTAINER_REGISTRY: springtodoapp
  IMAGE_NAME: todo-app

jobs:
  unit-tests:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Run Unit Tests
        run: mvn test

  integration-tests:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Run Integration Tests
        run: mvn verify -DskipUTs=true

  build-and-push:
    needs: [ unit-tests, integration-tests ]
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Build native image
        run: mvn -Pnative,aot-helper spring-boot:build-image -DskipUTs
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Docker tag and push image
        run: |
          docker tag docker.io/library/${{ env.IMAGE_NAME }}:0.0.1-SNAPSHOT ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} 
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
